### ISSUE TITLE
Support for GHC 8.6

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#105]
# TODO:
- [ ] Make sure dotenv works with GHC 8.6
- [ ] Add the version 8.6 to the `.travis.yml` file

**Comment by ibarrae** [comment]
Mind if I take this one @CristhianMotoche?

**Comment by CristhianMotoche** [comment]
Go ahead @ibarrae Thanks.

**Comment by CristhianMotoche** [comment]
In favor of #106
