### ISSUE TITLE
Split library features into different projects

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#126]
Hello everyone!

Currently, our library has a couple of features that I think we should put into different projects that extend the basic `dotenv`:

1) [`configExamplePath`](http://hackage.haskell.org/package/dotenv-0.8.0.7/docs/Configuration-Dotenv.html#t:Config) in `configExamplePath`, which gives `dotenv` the ability to check for another `.env` file before loading the env variables.
2) [`loadSafeFile`](http://hackage.haskell.org/package/dotenv-0.8.0.7/docs/Configuration-Dotenv.html#v:loadSafeFile) function, which validates the env value with the "type" in a `scheme.yml` file to match before loading the env variables.

Motivation:
1) Reduce the cyclomatic complexity added due to [additional checks](https://github.com/stackbuilders/dotenv-hs/blob/master/src/Configuration/Dotenv.hs#L73-L78)
2) Keep the required dependencies. Currently, we're using `yaml` which is kind of heavy for the `loadSafeFile` functionality.
3) It generates heavy binary files. Check out the ones here: https://github.com/stackbuilders/dotenv-hs/releases/tag/v0.8.0.4 The `dotenv` binary file is around `14 MB`

Benefits:
1) Each library will focus on their own features
2) Users will decide which features from `dotenv` works best for them

Caveats:
1) This will be a major change that will **break** the current `dotenv` interface, so users will have to look for the libraries they want to add and update their dependencies
2) We'll have to maintain multiple libraries.

Please, let me know your thoughts on this proposal @sestrella @juanpaucar @jsl

**Comment by juanpaucar** [comment]
I think this is a good idea. From the pros and cons you've fleshed out, I think that it makes sense to make this change. We can see who has some time to work on this if your plate is full.

**Comment by CristhianMotoche** [comment]
As we've discussed with @sestrella, we're not going to split the library to segregate functionality. Nevertheless, we're going to deprecate the "type checking" feature which is adding yaml and increasing the dependencies of our project. Therefore, I'll close this issue for now in favor of #127 Thanks for taking a look @sestrella and @juanpaucar
