### ISSUE TITLE
Drop "Type Checking Envs" support

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/dotenv-hs#127]
[yaml](http://hackage.haskell.org/package/yaml) is mostly used to parse the schema.yml which is used to t[ype-check environment variables](https://github.com/stackbuilders/dotenv-hs#type-checking-envs) at runtime, however, all functions defined at [System.Environment](http://hackage.haskell.org/package/base-4.15.0.0/docs/System-Environment.html) read values as String therefore values stored in environment variables need to be parsed again from a String value which defeats the purpose of declaring a schema file in the first place. On the other hand, yaml is a big dependency, so getting rid of it as a dependency is going to reduce the compilation time.

Most dotenv ports have a single responsibility "read env variables from a file" therefore in most cases libraries like this one don't even have dependencies and just export a single function:

- [Ruby](https://rubygems.org/gems/dotenv/versions/2.1.1?locale=en)
- [Node.js](https://www.npmjs.com/package/dotenv)

I think we should consider getting rid of "Type checking envs" and try to reduce the number of dependencies in the project.

**Comment by CristhianMotoche** [comment]
Solved in #136
