### ISSUE TITLE
Move from Travis CI to GH actions

### ISSUE THREAD

**Issue by fefi95** [stackbuilders/dotenv-hs#128]
We want to move from Travis CI to GH actions due to a change in its policies. The configuration for GH Actions should cover the same that Travis does, that is:

- [x] Common check on Linux. Build and tests for versions: `8.10,  8.8,  8.6,  8.4,  8.2, 8.0, 7.10`
- [x] Common check on OSX. Build and tests for versions: `8.10`
- [x] Bundle the project and create a release in GH based on a given tag.

**Comment by CristhianMotoche** [comment]
Thanks a lot @fefi95 for the contributions. I'm closing this issue now.
