### ISSUE TITLE
Release workflow - Update Cabal version to 3.4

### ISSUE THREAD

**Issue by fefi95** [stackbuilders/dotenv-hs#132]
Currently, the release workflow uses the version `2.4` of Cabal. We would want to update it to use `3.4` and update the commands to build the packages accordingly.

**Comment by CristhianMotoche** [comment]
Solved in #153 updated to use [cabal `3.6`](https://github.com/stackbuilders/dotenv-hs/blob/master/.github/workflows/build.yml#L20-L35)
