### ISSUE TITLE
Allow/Forbid duplicated env variables in file

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#147]
At the moment, the dotenv file load the first value from the file (refer to issue #121) which may/may not be expected. I would like to change this to allow/forbid duplicated env variables in the `.env` files. Something like this:
```
cat > .env

dotenv 'echo $FOO' --no-dups
[ERROR]: Env 'FOO' is duplicated in a dotenv file. Please, fix that (or remove --no-dups).
```

Additionally, we should add a comment in the README to let users know about the value that we'll get at the end if `--no-dups` is not given, which is the first env variable in the files at the moment.

**Comment by FranzGB** [comment]
I would like to work on this. What would be the default behavior? also should dotenv raise an error instead of continuing with the process?

**Comment by CristhianMotoche** [comment]
Hey @FranzGB To answer your questions:

> What would be the default behavior?

The default behaviour should be to allow duplicated variables and specifying in the README that we take the last one found to set up.

> also should dotenv raise an error instead of continuing with the process?

Yes, please, let's display an error like the one I mentioned above:

> $ dotenv 'echo $FOO' --no-dups
> [ERROR]: Env 'FOO' is duplicated in a dotenv file. Please, fix that (or remove --no-dups).

Thanks for contributing to Dotenv!
