### ISSUE TITLE
Make parsing function available in cabal package

### ISSUE THREAD

**Issue by Martinsos** [stackbuilders/dotenv-hs#158]
It would be awesome if you exported the parser function, so it becomes a part of the library!

For me, loadFile and parseFile don't give enough control, and I would prefer to have a function that is something like `parseDotEnv :: Text -> Either ParseError [(String, String)]`, that I can use directly.

I believe you have such function, called `configParser`, that combined with `parse` could play this role, but it is not exposed.

**Comment by CristhianMotoche** [comment]
Hey @Martinsos I think we could expose `configParser`. Then, you could use `megaparsec` to create the function you want:

```hs
import Configuration.Dotenv (configParser)
import Text.Megaparsec (parse)

parseDotEnv :: Text -> Either (ParseErrorBundle String Void) [(String, String)]
parseDotEnv = parse configParser ""
```

Could that work for your case?

**Comment by Martinsos** [comment]
> Hey @Martinsos I think we could expose `configParser`. Then, you could use `megaparsec` to create the function you want:
> 
> ```haskell
> import Configuration.Dotenv (configParser)
> import Text.Megaparsec (parse)
> 
> parseDotEnv :: Text -> Either (ParseErrorBundle String Void) [(String, String)]
> parseDotEnv = parse configParser ""
> ```
> 
> Could that work for your case?

Yup, that is looking pretty good!
You could probably even write and expose what you just wrote here, to have a nicer interface:
```hs
parseDotEnv :: Text -> Either DotEnvParseError [(String, String)]
```
that would be perfect, then I don't have to worry about the exact implementation.

I used `DotEnvParseError` because I am not sure what `ParseErrorBundle String Void` stands for, but I guess you could replace it with the simplest thing that makes sense but is also relatively general / known.

**Comment by CristhianMotoche** [comment]
Hey @Martinsos Dotenv uses [megaparsec](https://hackage.haskell.org/package/megaparsec) for the parsing and [`ParseErrorBundle`](https://hackage.haskell.org/package/megaparsec-9.3.0/docs/Text-Megaparsec-Error.html#t:ParseErrorBundle) is a collection with the errors it can find in a given text. Therefore, the parser (`configParser`) is all you need to define `parseDotEnv`. I can expose that in the next release.

**Comment by CristhianMotoche** [comment]
Hello @Martinsos In the version 0.11.0.1 I'm exposing the parser so that you can use it like I [mentioned here](https://github.com/stackbuilders/dotenv-hs/issues/158#issuecomment-1462876089).

**Comment by Martinsos** [comment]
Awesome, thank you!
