### ISSUE TITLE
Add a flag to allow verification of environment variables before program execution

### ISSUE THREAD

**Issue by FranzGB** [stackbuilders/dotenv-hs#159]
The current Dotenv CLI executes the program by utilizing the environment variables provided. 
The `--verbose ` flag can be used to display the loaded environment variables as shown in the following example: 

```
dotenv -f .env.db -f .env.api --verbose 'run.sh'
[INFO] DB_NAME = Prod
[INFO] DB_PASS = 1234
...
```

However, a concerning issue arises where the program will be executed regardless of the provided environment variables, even if they are missing or do not meet the required criteria. To mitigate this issue, it is recommended to implement a solution that allows for the verification of environment variables prior to program execution.
 
## Proposal:

As @jpvillaisaza mentioned we could implement a `--show` or a `--dry-run` flag that facilitates the user in examining the environment variables, without executing the program. The primary advantage of this approach is the prevention of program execution with incorrect or unsatisfactory environment variables.

**Comment by CristhianMotoche** [comment]
Hey @FranzGB I've assigned @flandrade to solve this issue. Could you please follow up with her on the development of this feature?
