### ISSUE TITLE
Introduce a .dotenv.config file to store and read flags for Dotenv CLI

### ISSUE THREAD

**Issue by FranzGB** [stackbuilders/dotenv-hs#160]
The current implementation of the Dotenv Command Line Interface (CLI) requires users to provide multiple flags in order to execute a program with specific environment variables. This can result in a lengthy and unwieldy command.

To address this issue, it is proposed that a `.dotenv.config` file be introduced. This file will contain the necessary flags to be passed to the CLI and will be read by Dotenv, allowing users to execute programs with the required environment variables in a more concise and streamlined manner.

This approach is inspired by the behavior of RSpec, a popular testing framework for Ruby. By introducing a `.dotenv.config` file, users will be able to more easily manage the necessary flags for their programs and streamline their workflow.

Example:
```
# .dotenv.config
-x .env.example
-x .env.example.db
-f .env.db 
```

**Comment by CristhianMotoche** [comment]
Hey @FranzGB I've assigned @flandrade to solve this issue. Could you please follow up with her on the development of this feature?

**Comment by aloussase** [comment]
Hi, what is the difference between the `-x` and `-f` flags?

**Comment by CristhianMotoche** [comment]
Hello @aloussase The difference is:

- `-x`(short for `--example`) - Example file. Those files have environment variables (not values) and they're used to enforce that the variables defined within them exist before continuing with the program execution
- `-f`(short for `--dotenv`) - Dotenv file. It's the file that will contain the environment variables (names and values) that will be loaded before a program execution.

I hope that is clear. I think we'll need to revisit our README.md to make this clearer.
