### ISSUE TITLE
Support optparse-applicative 0.18

### ISSUE THREAD

**Issue by modotte** [stackbuilders/dotenv-hs#166]
There has been a minor release with optparse-applicative that has moved to use [prettyprinter](https://hackage.haskell.org/package/prettyprinter) over deprecated [ansi-wl-pprint](https://hackage.haskell.org/package/ansi-wl-pprint) in 0.18 and 0.18.1.

It would be nice to have 0.18 supported. :confetti_ball:

**Comment by CristhianMotoche** [comment]
Hi @modotte Thanks for the suggestion. Indeed, that would be great! Thanks for reporting that!
