### ISSUE TITLE
Release 0.11.0.2 to Hackage?

### ISSUE THREAD

**Issue by tfausak** [stackbuilders/dotenv-hs#173]
Version [0.11.0.2](https://github.com/stackbuilders/dotenv-hs/releases/tag/v0.11.0.2) is tagged here on GitHub, but it hasn't been released to Hackage.

**Comment by CristhianMotoche** [comment]
Hi @tfausak My bad. I published the release but I forgot to rollout the candidate version. I'll do it right away! Thanks for reporting it.

**Comment by CristhianMotoche** [comment]
[Released](https://hackage.haskell.org/package/dotenv-0.11.0.2)!

**Comment by tfausak** [comment]
Thank you!
