### ISSUE TITLE
Review warnings on Publish Release

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#174]
We're getting the following messages when releasing `dotenv`:

```
There were some warnings:

    'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit and not just imposing longer compile times on your users.
    These packages miss upper bounds: - base-compat - containers - directory - hspec - shellwords - text Please add them, using `cabal gen-bounds` for suggestions. For more information see: https://pvp.haskell.org/
```

Let's review them and solve them.

**Comment by DanRCM** [comment]
Hi, I would like to solve this problem, could you assign me please?

**Comment by CristhianMotoche** [comment]
Go ahead! Thanks @DanRCM

**Comment by DanRCM** [comment]
Hi friend, I've been working lately on this issue, and currently most of the problem is solved, however <'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit and not just imposing longer compile times on your users.> it's unclear to me. I'm somewhat unfamiliar with testing using haskell, could you briefly tell me how to test in this case?

**Comment by CristhianMotoche** [comment]
Hello @DanRCM Thanks for taking a look at this issue. `-O2` will do an optimization during the compilation of the library. Although, that could increase the build time. I'm not sure how drastically that will affect, so I would suggest to some bench mark.  `time` can help to know how long it takes:

```
time cabal build
```

You'll need to double check in these two cases:

1) Build the library from scratch WITHOUT that flag.
2) Build the library from scratch WITH that flag. 

After that, compare the restuls. Is `-O2` affecting the build time drastically?

**Comment by DanRCM** [comment]
@CristhianMotoche Hello, I've been working on this. I would appreciate it if you could review the pull request and let me know if there are any areas I could improve, in case there are any issues.

**Comment by CristhianMotoche** [comment]
Thanks @DanRCM for working ont this issue. I think it's okay to close it now.
