### ISSUE TITLE
parseFile doesn't seem to escape characters as expected

### ISSUE THREAD

**Issue by Martinsos** [stackbuilders/dotenv-hs#186]
Here is an .env file I used to illustrate the potential issue:
```
TEST1="a\nb"
TEST2='a\nb'
TEST3=a\nb
TEST4="a\\nb"
```

Now, when I run `parseFile "testenv"` in `ghci`, I get the following output:
![image](https://github.com/stackbuilders/dotenv-hs/assets/1536647/10690d63-deb6-4674-85a2-d730c14f8685)

Formatted:
```hs
[ ("TEST1","anb"),
  ("TEST2","anb"),
  ("TEST3","anb"),
  ("TEST4","a\\nb"),
]
```

This is not the output I would expect though.

Output I would expect is the following:
```hs
[ ("TEST1","a\nb"),
  ("TEST2","a\nb"),
  ("TEST3","a\nb"),
  ("TEST4","a\\nb")  -- OK I am not 100% sure what to expect here, this might be ok.
]
```

Is my expectation wrong here, or is this potentially a bug in the Dotenv?

I am using `dotenv ^>= 0.10.0`.

Thanks!

**Comment by Martinsos** [comment]
Thanks @CristhianMotoche !

I don't care much about the "\\n" case, but "\n" being parsed as "n" is quite tricky, it makes it impossible to enter a string with a newline inside the env (and for example, Google gives you PEM key as a secret and it has newlines!). The only solution we found so far was to encode it with base64, putting it in .env like that, and then decoding it after being red for dotenv.

Let me know if I can help in some way!

**Comment by CristhianMotoche** [comment]
Hey @Martinsos I was able to reproduce the issue. Indeed, it seems something wrong in the parser. FWIW, I think you can add new lines instead of the `\n` character to represent new lines. For example:

Given this `.env`:

```
BAR="a
b"
```

`parseFile` will return:

```hs
ghci> parseFile ".env"
[("BAR","a\nb")]
```

I hope that works as a workaround until we find a solution for this issue.
