### ISSUE TITLE
Tests not running on Travis for GHC 7.6.3

### ISSUE THREAD

**Issue by jsl** [stackbuilders/dotenv-hs#22]
We're getting the following error in the build output on Travis. It appears that the program is building successfully, but the test suite is not running. Because of this, I'm not entirely sure if this package works on GHC 7.6. We get the following error in the build log:

```
cabal: Error: Could not find test program
"dist/build/dotenv-test/dotenv-test". Did you build the package first?
```

We may remove support for GHC 7.6 entirely in the future, since it's already pretty outdated. Leaving this issue here for the record until such a decision is made.

**Comment by jpvillaisaza** [comment]
@jsl I found two problems:

- The job for GHC 7.6.3 is using Cabal 1.16. For this version of Cabal, `cabal test` doesn't imply `cabal build` (Cabal 1.18 and newer versions do). This explains the "Did you build the package first?" issue.

- The `hspec-discover` executable was not in the path.

#23 fixes these problems. I'm not sure if this makes Travis CI take more time and whether there's a better solution, but the tests are now running for GHC 7.6.3.

@CristhianMotoche Is this problem similar to the ones we had for other libraries using `hspec-discover` and GHC 7.6.3? If so, here's a solution.

**Comment by jpvillaisaza** [comment]
Fixed. See ba97090.

**Comment by CristhianMotoche** [comment]
Great! I think we can still supporting GHC 7.6.3.
