### ISSUE TITLE
Allow megaparsec 5.0.0

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/dotenv-hs#25]
See fpco/stackage#1446.

To allow megaparsec 5.0.0, we have to fix the following error:

```
.../dotenv-hs/spec/Configuration/Dotenv/ParseSpec.hs:93:33:
    Expecting two more arguments to ‘ParseError’
    The first argument of ‘Either’ should have kind ‘*’,
      but ‘ParseError’ has kind ‘* -> * -> *’
    In the type signature for ‘parseConfig’:
      parseConfig :: String -> Either ParseError [(String, String)]
```

**Comment by jsl** [comment]
@jpvillaisaza I think [this](https://github.com/stackbuilders/dotenv-hs/tree/megaparsec-5.0.0) fixes the issue, but I'm not sure how to release it, since since I had to add megaparsec-5.0.0 to `extra-deps` to test, I'm not sure how to release this. Thoughts?

**Comment by jpvillaisaza** [comment]
@jsl We could change the version to 0.4.0 and only allow megaparsec >= 5.0.0, or use CPP to only change the upper bound of megaparsec. The former approach was used for language-thrift, which is also in the list (fpco/stackage#1446). I don't know if there are advantages with allowing older versions -- I think the 0.4.0 approach is good. For having megaparsec as an extra dependency, that should a problem only until megaparsec 5.0.0 makes it to Stackage Nightly and then LTS Haskell (and I guess Stackage will include an upper bound for dotenv until then). If we used CPP, then megaparsec wouldn't be an extra dependency.
