### ISSUE TITLE
Add Configuration.DotenvSpec Configuration.Dotenv.ParseSpec to other modules

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/dotenv-hs#4]
The `Configuration.DotenvSpec` and `Configuration.Dotenv.ParseSpec` are not part of the other modules field in the test suite, so there are no tests in the Cabal package.

**Comment by jsl** [comment]
@CristhianMotoche would you be able to take a look at this one? Seems like something we should fix.

**Comment by CristhianMotoche** [comment]
We could mark this as solved, since #9.

**Comment by jpvillaisaza** [comment]
@CristhianMotoche Thanks.
