### ISSUE TITLE
Make a "safe" wrapper for loading variables

### ISSUE THREAD

**Issue by jsl** [stackbuilders/dotenv-hs#41]
Following the example of dotenv-safe, we can be more helpful when loading environment data. We may be able to define types of variables to import, to specify variables that need to be specified, whether or not they need to have non-null contents, and perhaps other basic types.

One possible implementation that I discussed with @sestrella was that we may be able to allow the user to specify a template, perhaps in dotEnv format. The left hand side would specify variable names that could occur, and the right hand side may point to a type that could contain a parser defined in Megaparsec that is defined internally in dotenv. We should be able to specify whether or not a variable should be mentioned at all in the input file, and if it is mentioned, can it be null? Otherwise, should it be an integer, alphanumeric string, etc.

**Comment by jpvillaisaza** [comment]
The idea is https://www.npmjs.com/package/dotenv-safe, right?

@well1791 I think you and @sestrella have an initial idea ready. Would it make sense to add a comment here to discuss it and then work on it?

**Comment by well1791** [comment]
@jpvillaisaza Good idea.

@sestrella suggests me that we can define something like a _schema_ file to compare with the actual _.dotenv_ file e.g.

_.dotenv.schema_
```json
{
  "DB_HOST": {
    "required": true,
    "type": "string",
    "allowEmpty": false
  }
}
```

_.dotenv_
```
DB_HOST=localhost
```

So the operation that performs the checking will expect the path of those two files.

@jpvillaisaza what do you think?
\cc @sestrella @jsl

**Comment by jpvillaisaza** [comment]
Does it make sense to add command line options as well (perhaps as part of a separate issue/pull request)? I think it could make sense for an option like `--allow-empty-values` (which would affect all variables specified in the sample file).

Other than that, I guess the default value for an environment variable will be to require it (like dotenv-safe does). Thus, I'm not sure including both `required` and `allowEmpty` values is necessary -- just `allowEmpty` (or `allowEmptyValues`) should be enough (and the default value is false, which is like setting a required value to true).

Also, will this take place over the current executable or will it be two executables, one for an unsafe dotenv and another one for a safe version?

**Comment by well1791** [comment]
@jpvillaisaza I think it will be ok in the current executable, we can find if exists that `.dotenv.schema.json` file, and do the checking if we find it.

**Comment by sestrella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [dotenv - Make a "safe" wrapper for loading variables](https://trello.com/c/roFYGmY7/8-dotenv-make-a-safe-wrapper-for-loading-variables)

**Comment by CristhianMotoche** [comment]
@jsl @sestrella We already added the new feature of [dotenv-safe](https://github.com/stackbuilders/dotenv-hs/commit/0e08424c1f97ee3643246528547d9f6cb90ad98d). Does that solve the issue?

**Comment by jsl** [comment]
@CristhianMotoche I don't think that the pull request you mentioned addresses the issue of safety, at least as most Haskellers think of it. I would still like to see the addition of basic types to the library.

**Comment by CristhianMotoche** [comment]
@jsl Ok, I think I got the idea. Please, let me know if I'm going in the right way. My understand is that we want something like this:

![image](https://user-images.githubusercontent.com/8370088/29880795-54a50832-8d6e-11e7-97ed-133817fbdc5e.png)

Am I right?

**Comment by CristhianMotoche** [comment]
In the PR: #69 I'm reading a `.scheme.yml` that has the following structure: 
```
envs:
  - name: DOTENV
    type: bool
  - name: PORT
    type: integer
```
Then read the envs from the dotenv file and match the type with the content so that then we can do some patter match to check that the value can be [parsed as the type defined](https://github.com/stackbuilders/dotenv-hs/pull/69/files#diff-5b429449752b25d87f4755a3f3de6948R40). Currently, I'm doing pattern matching over a sum type called [EnvType](https://github.com/stackbuilders/dotenv-hs/pull/69/files#diff-bd2d25f7da64e3675c65a64ea76fcd4cR12).

**Comment by CristhianMotoche** [comment]
Currently, we are only parsing over three types: bool, integer, and text. Which other types should we parse? To add those types to the EnvType sum type.

**Comment by CristhianMotoche** [comment]
@jsl I think #69 will solve this issue. May we close this PR now?
