### ISSUE TITLE
--allow-empty-values option will break Windows compatibility

### ISSUE THREAD

**Issue by acamino** [stackbuilders/dotenv-hs#44]
The [documentation for `System.Enviroment#setEnv`](https://hackage.haskell.org/package/base-4.9.1.0/docs/src/System.Environment.html#setEnv) says:

> On Windows setting an environment variable to the empty string removes that environment variable from the environment. For the sake of compatibility, we adopt that behavior. In particular

```
setEnv name ""
```
has the same effect as

```
unsetEnv name
```

It also says that if we want to support empty environment variables, we have to use `System.Posix.Env.setEnv`. The problem with using this library is that will break the compatibility of `dotenv-hs` with Windows OS.

Should we care about Windows support?

/cc: @sestrella, @jsl, @mrkkrp, @CristhianMotoche

**Comment by CristhianMotoche** [comment]
I do think we should care about windows support. There are some Haskell developers that use Windows and may found this library useful.

I had this concern a long time ago, you can check #7. I think the only solution for compatibility is using CPP.

**Comment by jsl** [comment]
Dotenv has implementations in many other languages. Can someone check what other implementations do for this case? Once we gather that information, we can choose behavior for dotenv-hs - preferably, something that is relatively flexible and safe.

**Comment by CristhianMotoche** [comment]
I've tried the following `.env` file
```
FOO=
BAR=1234
```
with [js dotenv](https://github.com/motdotla/dotenv)
```
require('dotenv').config();

if(process.env.FOO === undefined){
  console.log("Foo is not set");
} else {
  console.log("Foo is set");
}

console.log('Foo', process.env.FOO);
console.log('Bar:', process.env.BAR);
```

and [ruby dotenv](https://github.com/bkeepers/dotenv).
```
require 'dotenv'
Dotenv.load('.env')

if ENV['FOO'].nil?
  print("Foo is not set\n")
else
  print("Foo is set\n")
end

print('FOO: ' + ENV['FOO'] + "\n")
print('BAR: ' + ENV['BAR'] + "\n")
```

In both cases the output is:
```
Foo is set
FOO:
BAR: 1234
```

Looking into the code, it seems they only use their own basic library to manage environmental variables:

- [js dotenv](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L63)
- [ruby dotenv](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/environment.rb#L20-L26)

**Comment by CristhianMotoche** [comment]
Just in case, I did the same example with dotenv:

```haskell
import Configuration.Dotenv
import System.Environment

main :: IO ()
main = do
  loadFile False ".env"
  foo <- lookupEnv "FOO"
  bar <- lookupEnv "BAR"
  case foo of
    Nothing -> putStrLn "Foo is not set"
    Just _ -> putStrLn "Foo is set"
  putStrLn ("Foo: " ++ show foo)
  putStrLn ("Bar: " ++ show bar)
```
And I got the following output:
```
Foo is not set
Foo: Nothing
Bar: Just "1234"
```

**Comment by habibalamin** [comment]
Wasn't there a related issue on this repository about blank environment variables not being set by `dotenv-hs`?

I remember commenting on that with a workaround (because it was a wontfix to preserve Windows compatibility), but that only works on Haskell source files. It won't work if you need to load your `.env` file with something like `dotenv -f .env -- command` (for example, with supporting scripts).

I think being able to have blank environment variables is useful, and I kind of resent the fact that this Windows is acting as a lowest common denominator here (no offence to the team here, I can understand why you made the decision).

**Comment by CristhianMotoche** [comment]
@habibalamin Yeah, there is a PR (#7) where we discussed a little bit about it. I think it is good to have an issue open. We can have further discussions.

**Comment by CristhianMotoche** [comment]
Closing this issue because of https://github.com/stackbuilders/dotenv-hs/pull/51#issuecomment-309638056
