### ISSUE TITLE
Drop support for GHC 7.6.3

### ISSUE THREAD

**Issue by acamino** [stackbuilders/dotenv-hs#45]
I found interesting that this library has backward compatibility with GHC 7.6.3.

We faced a compilation issue on CI with this GHC 7.6.3. To track down a bug we had to add more machinery, concretely a Docker container to reproduce the problem in isolation. If we drop the support for this version, we can depend only on _stack_ to seamlessly change the GHC version. 

I'd like to know if there any reason that justifies supporting GHC 7.6.3?

/cc @sestrella, @jsl, @mrkkrp, @CristhianMotoche

**Comment by mrkkrp** [comment]
I'm OK with dropping it. I recently dropped support for 7.6.3 in Megaparsec, next version will work with GHC 7.8+ only.

**Comment by CristhianMotoche** [comment]
@acamino and I are working in a branch with new features and it supports **GHC 7.6.3**. Perhaps, we could make a release of that (whenever our branch is merged) and support that version. After that, we can do another release, removing all the machinery and only working with **GHC 7.8+**.

**Comment by juanpaucar** [comment]
Since we are planned to move to Megaparsec 6.0, I'm also dropping support for GHC 7.6 here https://github.com/stackbuilders/dotenv-hs/pull/56

**Comment by juanpaucar** [comment]
This has been done in version 0.4.0.0 (https://hackage.haskell.org/package/dotenv-0.4.0.0)
