### ISSUE TITLE
Blank environment variables aren't loaded (even in a POSIX environment)

### ISSUE THREAD

**Issue by habibalamin** [stackbuilders/dotenv-hs#48]
I think being able to have blank environment variables is useful, and I kind of resent the fact that Windows is acting as a lowest common denominator here (no offence to the team here, I can understand why you made the decision).

Some conversation occurred on #7 and #44.

---

For those coming to this issue after a lot of conversation, [this bug is being tracked upstream](https://ghc.haskell.org/trac/ghc/ticket/12494), as it's a bug with GHC itself. I'll update this comment to keep track of the status of the bug.

**Comment by jsl** [comment]
Thanks @habibalamin! I'm leaning towards having an option as well to allow blank values. Maybe the default is to do whatever works on Linux / Mac and Windows users need to specify an option? I wish we could find precedent in another dotenv lib that we could use for inspiration. Feel free to post here if you have observed, or have time to research behavior in other dotenv libs (Node, Python, Ruby etc) that you like or dislike.

**Comment by habibalamin** [comment]
As it happens, @CristhianMotoche [did some tests](https://github.com/stackbuilders/dotenv-hs/issues/44#issuecomment-298200475) with the major Ruby & JS implementations and they both set blank variables. I'm not sure how those implementations would behave on Windows.

I also [noted](https://github.com/stackbuilders/dotenv-hs/pull/7#issuecomment-280747026) on #7 that there is [an open GHC bug ticket claiming that Windows *does*, in fact, support blank environment variables](https://ghc.haskell.org/trac/ghc/ticket/12494).

From what I can gather from a quick Google, most sources corroborate the original claim of Windows *not* supporting blank environment variables. This could be because:

  1. Repetition of the claim has made others believe it to be the truth and repeat it themselves.
  2. The [official Windows documentation linked to](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686206(v=vs.85).aspx) that suggests — and it does only suggest — that blank environment variables are supported is misleading.

**Comment by habibalamin** [comment]
```c
#include <stdlib.h>
#include <Windows.h>
#include <stdio.h>
#include <process.h>

int main(int argc, char *argv[])
{
  char test[50];

  SetEnvironmentVariable("TEST", "");
  GetEnvironmentVariable("TEST", test, 51);
  printf("TEST: '%s'\n", test);

  // searches PATH, inherits environment
  _execlp("cmd", "cmd", NULL);

  printf("exec failed!\n");
  return 0;
}
```

I tested this on a Windows 7 VM:

```
Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>cd Documents

C:\Users\IEUser\Documents>.\enver.exe
TEST: ''

C:\Users\IEUser\Documents>Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser\Documents>echo %TEST%
%TEST%

C:\Users\IEUser\Documents>.\enver.exe
TEST: ''

C:\Users\IEUser\Documents>Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser\Documents>echo %TEST%
%TEST%

C:\Users\IEUser\Documents>.\enver.exe
TEST: ''

C:\Users\IEUser\Documents>Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser\Documents>echo %TEST%
%TEST%

C:\Users\IEUser\Documents>
```

Perhaps more interestingly:

```
Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>cd Documents

C:\Users\IEUser\Documents>set TEST=test

C:\Users\IEUser\Documents>.\enver.exe
TEST: ''

C:\Users\IEUser\Documents>Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser\Documents>echo %TEST%
test

C:\Users\IEUser\Documents>.\enver.exe
TEST: ''

C:\Users\IEUser\Documents>Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser\Documents>echo %TEST%
test

C:\Users\IEUser\Documents>.\enver.exe
TEST: ''

C:\Users\IEUser\Documents>Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser\Documents>echo %TEST%
%TEST%

C:\Users\IEUser\Documents>
```

It forgets the environment variable on the third — consistently the third — nested exec call, but it *doesn't* unset it the first time it's set to the empty string. The documentation suggests that it would be unset if it were given an argument of NULL, but it didn't say anything about giving it an argument of a blank string, so that's technically valid.

Incidentally, I did also test `SetEnvironmentVariable` with a null value and that doesn't forget either, so the documentation seems to be inapplicable for whatever reason (it's possibly referencing Windows 8).

The most interesting finding is that when calling `GetEnvironmentVariable`, everything behaved as expected; blank environment variables were actually printed as blank (well, not printed), and when set to NULL, printing the environment variable results in funny characters being printed.

It could be that Windows *does* support blank environment variables under the hood, but the `cmd.exe` shell itself simply treats those variables as unset. In that case, it seems perfectly fine to use in our own programs, but I'm speculating.

**Comment by habibalamin** [comment]
I'm going to be removing the VM, by the way, so if there's any particular tests you want me to do, you have 4 hours.

**Comment by CristhianMotoche** [comment]
Thanks for the research @habibalamin. I think the problem we have is that we cannot set env vars in POSIX environments. That is because the way `setEnv` in `System.Environment` is [defined](http://hackage.haskell.org/package/base-4.9.1.0/docs/System-Environment.html#v:setEnv). Right?

Could you please test other dotenv libraries from other languages (JS, Ruby, or Python) and see what is their behaviour? You could use the examples that [I did](https://github.com/stackbuilders/dotenv-hs/issues/44#issuecomment-298200475)

**Comment by habibalamin** [comment]
I shut down the machine, and it's now updating 🙄, but I'll test that once that's done.

Yes, the default `setEnv` is defined to not be able to set blank environment variables for consistency. The `unix` package (which contains `System.Posix.setEnv`), as expected, won't build on the Windows system without something like Cygwin; I haven't tried with Cygwin, but I'll try that too.

We could also just define our own `setEnv` that allows blank environment variables on both Windows and POSIX, but that sounds like perhaps the effort/readability/maintainability burden isn't worth it, although I wouldn't know (we'd probably have to interact with the FFI).

**Comment by CristhianMotoche** [comment]
Another solution could be using CPP like in #7. However, I'm not sure if we want to use CPP for that.

**Comment by habibalamin** [comment]
Okay, Ruby 2.3.3's [`Kernel#exec`](http://ruby-doc.org/core-2.3.3/Kernel.html#method-i-exec) inherits the environment:

```
Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>irb
irb(main):001:0> ENV['TEST'] = 'test'
=> "test"
irb(main):002:0> exec 'cmd'
Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>echo %TEST%
test
```

I had the same result as in C here. Setting a blank environment variable is retrievable through the language, but when spawning a `cmd.exe` process, it treats blank environment variables as unset:

```
Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>irb
irb(main):001:0> ENV['TEST']
=> nil
irb(main):002:0> ENV['TEST'] = ''
=> ""
irb(main):003:0> ENV['TEST']
=> ""
irb(main):004:0> exec 'cmd'
Microsoft Windows [Version 6.1.7601]
Copyright <c> 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>echo %TEST%
%TEST%
```

Perhaps Ruby or Windows' C API just store blank environment variables in a special place outside of the actual environment and that's why the shell doesn't recognise it; I tested that by `exec`ing two programs I controlled.

First, I modified the C program to this:

```c
#include <stdlib.h>
#include <Windows.h>
#include <stdio.h>
#include <process.h>

int main(int argc, char *argv[])
{
  char test[50];

  SetEnvironmentVariable("TEST", "");
  GetEnvironmentVariable("TEST", test, 51);
  printf("TEST: '%s'\n", test);

  _execlp("ruby", "ruby",  "enver.rb", NULL);

  printf("exec failed!\n");
  return 0;
}
```

and created a Ruby program like this

```ruby
puts "TEST: #{ENV['TEST'].inspect}"
```

The output is as you would expect:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>cd Documents

C:\Users\IEUser\Documents>.\enver
TEST: ''

C:\Users\IEUser\Documents>TEST: ""
```

Some timing issues, but it makes the point. Of course, when passing `NULL` to `SetEnvironmentVariable`, I get:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>cd Documents

C:\Users\IEUser\Documents>.\enver
TEST: 'íéh▀■   ┌ÿ►v·á◄v░♫''

C:\Users\IEUser\Documents>TEST: nil
```

Then I did it the other way around:

```ruby
puts "TEST: #{ENV['TEST'].inspect}"
exec '.\enver'
```

```c
#include <stdlib.h>
#include <Windows.h>
#include <stdio.h>
#include <process.h>

int main(int argc, char *argv[])
{
  char test[50];

  GetEnvironmentVariable("TEST", test, 51);
  printf("TEST: '%s'\n", test);

  return 0;
}
```

Here's the output of that:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>cd Documents

C:\Users\IEUser\Documents>ruby enver.rb
TEST: nil
TEST: '╨d╡4■   ┌ÿ►v·á◄v└♫X'

C:\Users\IEUser\Documents>set TEST=test

C:\Users\IEUser\Documents>ruby enver.rb
TEST: "test"
TEST: 'test'

C:\Users\IEUser\Documents>
```

I think this is good evidence that it's being stored in the actual environment, as it's being transferred cross-language as we would expect.

Here's what I got for the `dotenv` gem with your `.env` example in #44:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>cd Documents

C:\Users\IEUser\Documents>ruby dotenv.rb
Foo is set
FOO: ""
BAR: "1234"

C:\Users\IEUser\Documents>
```

Although I slightly modified the program (Rubyists use string interpolation, which automatically calls `#to_s` on the value; `string1 + nil + string2` explodes, but `"prefix#{nil}suffix"` evaluates to `"prefixsuffix"`):

```ruby
require 'dotenv'

Dotenv.load('.env')

if ENV['FOO'].nil?
  puts 'Foo is not set'
else
  puts 'Foo is set'
end

# fun fact: #inspect is Ruby's equivalent of Haskell's `show`;
# every object has it by default, except when inheriting from
# BasicObject.
puts "FOO: #{ENV['FOO'].inspect}"
puts "BAR: #{ENV['BAR'].inspect}"
```

I used your example for `node` and I actually was not expecting this:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser>cd Documents

C:\Users\IEUser\Documents>node dotenv.js
Foo is not set
Foo
Bar 1234

C:\Users\IEUser\Documents>
```

That looks like everything.

**Comment by CristhianMotoche** [comment]
@habibalamin Amazing job! Thanks a lot for your research. Now we understand in a better way the behaviour of Windows with empty env vars.

Well, now, for the matter of having blank env vars. We can make a list of the possible solutions and then choose one, or in the other hand not allow empty env vars.

**Comment by CristhianMotoche** [comment]
Feel free to add your solution:

- **Create an FFI** that works in both OS.
- **Using CPP** to load `System.Posix.setEnv` when the OS is not Windows.

**Comment by habibalamin** [comment]
Quoting from my other comment:

>I realise the danger of adding complexity through feature toggles, but allowing the user to pick their poison seems like the right option for situations where neither option is entirely without issue. Maybe a `--unix`/[`--allow-empty-values`](https://github.com/stackbuilders/dotenv-hs/issues/44) flag [would be useful].

In this case, this is another step we might want to take if we go for the blank environment variables only on POSIX option. This would allow the users to decide whether they want a consistent experience on all platforms (good for teams) or improved semantics for their preferred platform (good for homogenous teams/individuals).

The FFI option is probably going to take longer, but I will take a quick look at that and see what I can do.

**Comment by habibalamin** [comment]
@CristhianMotoche if you look at the PR, you can see I had trouble with setting blank environment variables across the FFI, despite the fact that I can do it directly in C and the Ruby API allows it.

I thought it might have something to do with sending `CString` values across the FFI, but I also created a dedicated function with no arguments that itself calls `SetEnvironmentVariable` with a blank string directly in C, and that didn't work either.

I'd like it if someone could take a look at the PR, see if I missed anything, but I don't have high hopes. This problem could be why the GHC folks thought Windows doesn't support blank variables too, and Node doesn't seem to allow it, so they either didn't want to or had issues, too.

I could take a look at the Ruby project C source and see how they do it, but our best option is looking like support for UNIX only (possibly with a flag, so that the default is consistency across platforms).

**Comment by habibalamin** [comment]
[The way Ruby does it](https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/tags/v2_4_1/hash.c?revision=58053&view=markup#l3383) is very complex. Obviously, there's some extra work for platforms like Solaris there, but it seems unwieldy and like something we don't want to adopt for something that should be so basic.

I'm not sure how it works, and it would probably take me hours or days to figure it out (I can get by in C, but I don't _really_ know it or use it).

So, I propose we just ignore Windows support for this. Ideally, we'd default to consistency on all platforms, and use a flag to enable the feature for teams who exclusively use Unix platforms.

**Comment by CristhianMotoche** [comment]
Closing this PR because of https://github.com/stackbuilders/dotenv-hs/pull/51#issuecomment-309638056

**Comment by CristhianMotoche** [comment]
I'll let this issue open, because this is a problem that we shouldn't fix here. However, if you want to have empty env vars you could use something like the code below in your configuration.

```haskell
fromMaybe "" <$> lookupEnv "ENV_VAR"
```
For instance, if `ENV_VAR` is empty or not set it will be "" in your configuration, otherwise it will be any value you have in `ENV_VAR`.

**Comment by habibalamin** [comment]
You can track the progress of [this bug upstream](https://ghc.haskell.org/trac/ghc/ticket/12494) (it's technically a GHC bug).

**Comment by habibalamin** [comment]
This has been [fixed upstream](https://phabricator.haskell.org/D3726), and is slated for the 8.4.1 release, which [looks like it's going to be released on the 18th January 2018 12am (~6 months from now)](https://ghc.haskell.org/trac/ghc/milestone/8.4.1).

**Comment by CristhianMotoche** [comment]
😮 Great! Thanks for the news @habibalamin 😄

**Comment by habibalamin** [comment]
So now that the latest version of [`base`, 4.11.0.0](https://hackage.haskell.org/package/base-4.11.0.0), that was uploaded to Hackage on Monday, includes [`System.Environment.Blank`](https://hackage.haskell.org/package/base-4.11.0.0/docs/System-Environment-Blank.html), I think we ought to look back into this.

I know there are backward-compatibility (and forward-compatibility) concerns. Eventually, `System.Environment.Blank` will be folded into `System.Environment` in the next major GHC version (IIRC).

**Comment by CristhianMotoche** [comment]
Awesome. Thanks a lot @habibalamin

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Blank environment variables aren't loaded (even in a POSIX environment)](https://trello.com/c/cnMVbdLy/42-blank-environment-variables-arent-loaded-even-in-a-posix-environment)

**Comment by CristhianMotoche** [comment]
@habibalamin I just pushed `0.8.0` to [hackage](https://hackage.haskell.org/package/dotenv-0.8.0.0).
I suppose we can close this issue now. Thanks a lot for your contribution. :grin:

**Comment by habibalamin** [comment]
Wowee, what a journey.
