### ISSUE TITLE
Upgrade Travis CI to container-based infrastructure

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/dotenv-hs#5]
See [multi-ghc-travis](https://github.com/hvr/multi-ghc-travis) for instructions on how to set up Travis with container-based infrastructure and caching of dependencies.

**Comment by jsl** [comment]
Hi @jpvillaisaza - I updated the .travis.yml today, based on the latest recommendations from Stackage. I think that my changes cover these concerns, so I'm closing this issue, but please feel free to open this or another issue if you have other suggestions.

**Comment by jpvillaisaza** [comment]
@jsl Great! I think the changes cover more than I had in mind. I like that you included OS X as well (they seem to take more time, but not too much).
