### ISSUE TITLE
.envs as Ciphertext

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#64]
## Motivation
Setting things like passwords, key phrases, tokens, and so on is very common in .envs. As well as sharing `.envs`, specially when someone new enters into a project. Of course, having a security culture won't allow that this kind of things happen. However, we can make sure that they don't happen by adding `.envs` as cipher text.

## Description
Given a `.env` and a password we can generate a `.env.cipher` that will have the `.env` vars as ciphertext.
![image](https://user-images.githubusercontent.com/8370088/30328557-4ead0e4e-9795-11e7-856b-cc7aeeef2f25.png)

In order to load this `.env` vars, we could set a flag in the command line. Internally it will load the env vars in the environment.
![image](https://user-images.githubusercontent.com/8370088/30328437-f7673d4e-9794-11e7-8f8a-db2c70621b40.png)

It will be similar to the way ansible vault saves secret files.

@jsl @juanpaucar @sestrella 
This is just an idea that came to my mind in a dream (just kidding). I'd like to know what do you think. Is it worth to work on it? Or add it?

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [.envs as Ciphertext](https://trello.com/c/ax7BXjfi/39-envs-as-ciphertext)

**Comment by CristhianMotoche** [comment]
I think there is already a library for this purpose, thought, the variable codification is different: https://github.com/CollegeVine/confcrypt#readme
In case we want to add this complexity, I think it would be better to have a second repo for this purpose.
