### ISSUE TITLE
List, Add, Set, Delete env vars from CLI

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#67]
## Motivation
Usually, when a user wants to set/add/list/delete an env var. He/She needs to open the file and then modify it. I think it could possibly be useful to directly from `dotenv` CLI to set/add/list/delete the env vars in the `.env` file.
For instance:
```
$ dotenv list
Envs:
- FOO=bar
- BAR=baz

$ dotenv add "BAZ" "foo"
Envs:
- FOO=bar
- BAR=baz
- BAZ=foo

$ dotenv set "BAZ" "foobar"
Envs:
- FOO=bar
- BAR=baz
- BAZ=foobar

$ dotenv del "BAZ"
Envs:
- FOO=bar
- BAR=baz
```
Does this make sense? Or do you think it could be useful?
Please, let me know your concerns @jsl @juanpaucar @sestrella

**Comment by juanpaucar** [comment]
I think it's a good idea. But, I also have a question @CristhianMotoche. What would happen in the case that an example file is passed, should dotenv remove the variable from it too?

**Comment by CristhianMotoche** [comment]
I think it should search trough all the `.env` files given to the CLI and `.env` by default.

**Comment by CristhianMotoche** [comment]
Actually, I found this feature bothering. For instance, if I have a variable "DB_NAME" with value "my_application_db" and I want to set the value to "my_application_test_db", the command will be like:

```
$ dotenv set DB_NAME my_application_test_db
```

Which is bothering and it requires more typing than simply opening a file, set the value and set the file.
And for the listing...

```
$ cat .env
```

Will do the same.

So... I'm closing this issue
