### ISSUE TITLE
Allow empty .env file

### ISSUE THREAD

**Issue by felixSchl** [stackbuilders/dotenv-hs#70]
Is there any particular reason that the .env file must not be empty? It fails to parse because it currently requires at least one variable be set.

```
Failed to read fileParseError {
errorPos = SourcePos {
    sourceName = ".env",
    sourceLine = Pos 2,
    sourceColumn = Pos 1
} :| [],
errorUnexpected = fromList [EndOfInput],
errorExpected = fromList [Label ('v' :| "ariable name")],
errorCustom = fromList []
}
```

**Comment by CristhianMotoche** [comment]
Currently, we don't accept empty `.env` files. However, I don't think that should happen. I'll be working on that this week. Thanks.

**Comment by CristhianMotoche** [comment]
@felixSchl It is already on [hackage](http://hackage.haskell.org/package/dotenv-0.5.1.1)
I'll be closing this PR.

**Comment by felixSchl** [comment]
Wow that was fast, thanks!
