### ISSUE TITLE
Upgrade to Stack LTS 4.0

### ISSUE THREAD

**Issue by jsl** [stackbuilders/dotenv-hs#8]
We can upgrade to the latest Stack LTS version.

/cc @CristhianMotoche, feel free to take this one if you want. :)

**Comment by CristhianMotoche** [comment]
I think we could mark this as solved, since #10.

**Comment by jsl** [comment]
Sure, I'll close this. However, feel free to upgrade to 4.1 - I think that's the latest now?

**Comment by CristhianMotoche** [comment]
Yeah, actually they will release LTS 5 this Sunday, so I'll upgrade it this Sunday.
