### ISSUE TITLE
Ambigious occurrence 'many'

### ISSUE THREAD

**Issue by tomjaguarpaw** [stackbuilders/dotenv-hs#85]
I'm trying to compile `dotenv-0.5.2.1` (a dependency of Opaleye).  I get the error

```
src/Configuration/Dotenv/Parse.hs:45:39: error:
    Ambiguous occurrence ‘many’
    It could refer to either ‘Control.Applicative.many’,
                             imported from ‘Control.Applicative’ at src/Configuration/Dotenv/Parse.hs:21:1-36
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.Megaparsec.many’,
                             imported from ‘Text.Megaparsec’ at src/Configuration/Dotenv/Parse.hs:24:1-32
                             (and originally defined in ‘parser-combinators-0.4.0:Control.Monad.Combinators’)
```

Indeed `Configuration.Dotenv.Parse` imports both `Control.Applicative` and `Text.Megaparsec`.  [`Text.Megaparsec`](https://hackage.haskell.org/package/megaparsec-6.4.0/docs/Text-Megaparsec.html) rexports [`Control.Monad.Combinators`](https://hackage.haskell.org/package/parser-combinators-0.4.0/docs/Control-Monad-Combinators.html) which indeed defines its own `many` since 0.4.0.  (I don't know why).  Thus the name `many` is ambiguous inside `Configuration.Dotenv.Parse`.

I'm a bit puzzled since it's hard to understand why I seem to be the first person to notice this.

**Comment by CristhianMotoche** [comment]
@tomjaguarpaw Actually, the people from Stackage told us about this issue: https://github.com/fpco/stackage/issues/3159 We fixed that in the last release.

**Comment by tomjaguarpaw** [comment]
Ah, yes that's great.  I see the fix here in 0.5.3.1: https://hackage.haskell.org/package/dotenv-0.5.2.3/docs/src/Configuration-Dotenv-Parse.html#configParser

I wonder why my install plan is giving me an older version.  Is it possible you could submit a Hackage revision to change the upper bound on `megaparsec` in the affected versions?

**Comment by tomjaguarpaw** [comment]
Ah, the new version didn't exist when my CI job was kicked off!  I have restarted it: https://travis-ci.org/tomjaguarpaw/haskell-opaleye/builds/327212150

**Comment by CristhianMotoche** [comment]
Your CI is passing now. 😃

**Comment by tomjaguarpaw** [comment]
Fabulous.  Thanks for the quick response!

**Comment by tomjaguarpaw** [comment]
(FWIW it might be best to blacklist those old versions)
