### ISSUE TITLE
Rename scheme with schema

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#87]
@dbalseiro Suggest that we should rename the word `scheme` with `schema` which would be a better name.

**Comment by juanpaucar** [comment]
scheme:
```a large-scale systematic plan or arrangement for attaining some particular object or putting a particular idea into effect.```

schema:
```a representation of a plan or theory in the form of an outline or model.```

**Comment by CristhianMotoche** [comment]
@juanpaucar Thanks for the references. I think the `.schema.yml` is an outline for the type checking.

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename scheme with schema](https://trello.com/c/2jwXDlVz/38-rename-scheme-with-schema)
