### ISSUE TITLE
Handle exceptions

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#88]
I think we are using many time `error` in the application. However, I don't think that is the correct way to handle some errors. Perhaps, we should start using an [specific exception](http://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Exception-Base.html#t:Exception) type.

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle exceptions](https://trello.com/c/gq1OnjDo/37-handle-exceptions)

**Comment by CristhianMotoche** [comment]
I think it make sense to use `error` to stop a program's execution for now. Exceptions shouldn't be necessary in this case. So, I'll close this issue for now.
